### ISSUE TITLE
softmax_cross_entropy_with_logits報錯誤

### ISSUE THREAD

**Issue by kennylovesfree** [c1mone/Tensorflow-101#3]
剛開始學習, 很開心看到有這個資源
但執行到softmax_cross_entropy_with_logits時
報出以下錯誤: ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
不知道是為什麼呢?

**Comment by c1mone** [comment]
看起來應該是版本的因素，我使用的時候不是 1.0 版，等等來查查看．

**Comment by c1mone** [comment]
改成這樣即可
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = y_conv, labels = y_))

**Comment by kennylovesfree** [comment]
恩恩~~太感謝了! 已經沒問題
